name: tamizshahr
description: Appliction of Tamiz Shahr

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  shared_preferences:
  http:
  intl:
  flutter_widget_from_html_core:
  #  share: ^0.6.3+5
  #  image_picker: ^0.6.2+3
  url_launcher:
  html:
  flutter_spinkit:
  #  flutter_masked_text: ^0.8.0
  shamsi_date:
  carousel_slider:
  google_map_location_picker:
    git:
      url: https://github.com/humazed/google_map_location_picker.git
  google_maps_flutter:
  google_maps_flutter_platform_interface:
  plugin_platform_interface:
  geolocator:
  #  font_awesome_flutter: ^8.8.1
  fluttertoast:
    git:
      url: https://github.com/ponnamkarthik/FlutterToast.git

  cupertino_icons:
dependency_overrides:
  plugin_platform_interface:
  google_maps_flutter_platform_interface:
dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tamizshahr_600.png"
#  material_design_icons_flutter: 4.0.5345

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/splash_main.png
    - assets/images/main_page_header.png
    - assets/images/main_page_request_ic.png
    - assets/images/main_page_article_ic.png
    - assets/images/main_page_paper_ic.png
    - assets/images/main_page_shop_ic.png
    - assets/images/main_page_wallet_ic.png
    - assets/images/address_page_header.png
    - assets/images/login_bg.png
    - assets/images/phone_icon.png
    - assets/images/instagram.png
    - assets/images/telegram.png
    - assets/images/circle.gif
    - assets/images/circle2.gif
    - assets/images/orders_list.png
    - assets/images/message_icon.png
    - assets/images/user_Icon.png
    - assets/images/cash_pay_header.jpg
    - assets/images/wallet_money_bg.png
    - assets/images/collect_list_header.png
    - assets/images/donation_ic.png
    - assets/images/messages_screen_mail_ic.png
    - assets/images/send_popup_tick.png
    - assets/images/waste_cart_weight_ic.png
    - assets/images/waste_cart_price_ic.png
    - assets/images/tamizshahr_600.png

  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Iransans
      fonts:
        - asset: assets/fonts/IRANSansMobile.ttf
        - asset: assets/fonts/IRANSansMobile_Bold.ttf
        - asset: assets/fonts/IRANSansMobile_Light.ttf
        - asset: assets/fonts/IRANSansMobile_UltraLight.ttf
          weight: 700
    - family: IransansNonEn
      fonts:
        - asset: assets/fonts/IRANSansMobileNoEnMedium.ttf
          weight: 700
    - family: BFarnaz
      fonts:
        - asset: assets/fonts/B_Farnaz.ttf
          weight: 700


