name: recycleorigin
description: Application of RecycleOrigin

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.8+8

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  shared_preferences: ^2.3.3
  http: ^1.4.0
  intl: ^0.20.2
  flutter_widget_from_html_core: ^0.15.2
  url_launcher: ^6.3.1
  html: ^0.15.5
  flutter_spinkit: ^5.2.1
  #  shamsi_date: ^1.0.4
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.10.0
  fluttertoast: ^8.2.8

  cupertino_icons: ^1.0.5
  badges: ^3.1.2
  geolocator: ^14.0.0
  flutter_osm_plugin: ^1.3.7
  dartz: ^0.10.1
  loading_animation_widget: ^1.3.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: any
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Iransans
      fonts:
        - asset: assets/fonts/IRANSansMobile.ttf
        - asset: assets/fonts/IRANSansMobile_Bold.ttf
        - asset: assets/fonts/IRANSansMobile_Light.ttf
        - asset: assets/fonts/IRANSansMobile_UltraLight.ttf
          weight: 700
    - family: IransansNonEn
      fonts:
        - asset: assets/fonts/IRANSansMobileNoEnMedium.ttf
          weight: 700
    - family: BFarnaz
      fonts:
        - asset: assets/fonts/B_Farnaz.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          weight: 700


